services:
  - type: web
    name: namasthe-telangana-crm
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5050
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://namasthe-telangana-crm.onrender.com
